### 1. 유저 회원 가입 등록
POST localhost:8080/api/v1/users/signup
Content-Type: application/json

{
  "email": "test1@naver.com",
  "password": "password",
  "username": "test1",
  "nickname" : "test1",
  "profileUrl" : "test1@naver.com"
}


### 2. 유저 로그인
POST localhost:8080/api/v1/users/signin
Content-Type: application/json

{
  "email": "test1@naver.com",
  "password": "password"
}

